apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgABmHCtFqkUKxhzIvYnV7e5tvSti8IJOJJNktPsd5NBv1+asEPIkIQv3CmyB6vOe+0JG7lSjDhYjCWrppiuEfATcdxEfiBj571OvNuC92HQEfQjL6uCAq6ezkK39auhnrb373vaePBmiPH7Y2SApXtCbWaeCd0yOugDfJEeAhR2/0WSqEuttWIrw8tzo12eFZi8NZsmqwugQXfcYqbxWWtbgnmieTg05GqrVrW8HwzhLPJsdOzmdBB7Qu8RpVCU9nv5gW7c3euIjkFYHHmzvLjRAlOqflbEjOXwel7rrIAXj5k/9C6mj/EpVLCSZLb7xvEdSWVyQFe/9lqenTXznRYI95daNjRE38mqjs4VSWNX5OfyC+B9zggZk4+u764xgvrkLMgnUf9gPoqGjzxMyNvse2jh454tlwdH0fxJ+qA0f9WGMyVwV8UZb/68H1OF6CXREHn0biZaEfNaw0pSjevu2ItHd+iMBL7IkpXz/5Bx1IZSfI3F/VmZr57f9psMRXH/APEL99Im5/sS6vsV9QT/p40fSQ2LGw9wKjSJM+qvW6eyauvD7GLUBwSQjBsCMdK+UmhyHVHNbbgyo/k1CcooPKC8/X2AKuvDUSW0RC3WPntnov4lBaxqRYy/CqCdp1rhW1iVNr3udARJNnO3G/tR9vtWICIqDdSCjyRwNNNInNf/i7eHrboIm1/JUMlsmNm6gitP5l6svRvlaEbtIZidcai7XV/HB9MTyEVSoqrYHd7kML0MttlaC2E2jxQeAjmrTpAXrxjdz3fLZnL0aP00apimXrGiwPjQfzXY/FVQ2yqbwUR77S9XggEEwg6JgjpSeKsNlxvRfcGfb13NT0KXIN7kJUrT2Xw7iTfY/tMt41ACfHbz6kY/UNoy3rQnD6smhNKWph/OqF08FDbs4eGLJxbFDZZTwwTagMXjJWN74nWd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

