apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBVYmX2+B3IdRgP2YzVP/WdU1O2eM9IyKcvw9412p/AUrFGQZtpp/3wLHBj4NS7aZdolyeFmi7oXtcSdCeB5Ax7RXY2RWCs57iO6A0dd+HlPnaLKq5NAltRxWbEJFOgqLgOOHis3zcZ3pBGb/wXkvGLWltgbiW6pYNH/D07vm6dXdr7l0zvGHBKsfJX8Yb9uQIc3qpXRCDFTOiULsyZtP5tiaaWr/sQAUcS5jKBTXRVyRaaE6IUshPg80ktjNkiaNFve1sOJP+iNuRjwnITjjdSX01ypZ+megUb618OdNX81BNDI8QFIifx/pbpy4vWA30WHEXfiNCHh/rXCnE6jsqRMFZCrcPu0XeiPzXrLYVk8iPBelytDag90BO1rjn6a91ppO5kXiDpSnEMd7sbvk7aL94pDI9xJJSExHMnP2oKBNB+cp8752j+LrBSGhuuE4mxodGPYLmqjK/aYLy/JmFJ+TiH+hE8q9vP10Zmdsw3hFGQ9mEbjA8hGZ/0Jn8LNn/b4kYItci93ZyNmGIRaaDbaJabGFRVEWSIQiq75WTGtj7ZFQZYKpMmuEUmbhPLOGMyx5T4n/GMqHgUA8Vzb2+IcRUMUO6Sy7VemAE+jPrkIYk4T4TtI8VpzZk7R144T23Mr0Y2UfJwU57g3cVAf2EjwDcLosMBpovuM44IN+/m4PBpTFQOXM+zihcYOky5a3hkp0Q6XgZ6rsvrSdSoetczIFW0d0ysuenUWUkRk135Q5e3z08+iDWslrxJd/jT+QGWTM+iM/FlzEkACpLhqREQ3MwwRYED0aqWkQkLcJYv6rmZnsAp9bpECehsXIFUdLImf6yUNvAx5/qU7wIT9M1Q6+jV3Yew1gzoePTwL1AvruREKbRm/aMbcmWE/4UpP7GTE6sqSrkMJx9deFccvlkEZO5dLZJHi8Ft0Lqy7eRXojkD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

