apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAF6Ww3eZy3KCcjl03Ib0YvvzlsbdyTlaY4FcUVssyE6GQwm8s5BUgOMvhIKf4r43tRfHsivIG8D/WG6d98GsfRSuA5K/+yXP2co/RO7rg4+vg4XHylOiHkL0HdyOVnITgFTTv8evChrLZ47cxyQxkXFv3kuG6VzYRpS5IZkmSqdxfdglSJHnk1RmvAZkPdlssm5e7wllh4DsS4hZVs/Y5TFH9i4TyVNYoWa9AmBx2ywrrk2qIWJcvub3skP5AXdwOtepsxL+imgMmLFGti6qCtXALDCD+nCGWhfg53PkmwIIPrFIGKMEnWJ2QlBxGDGWK4rctvc0t2k9ZvMGOIOMQbCX0/Yw5U4fspw415WoH+Vs2pqGqcsfcNTZzN9pN8VYuMmHqQ5eBcD1jGkP5QZSjuQnG2GeJfc7EvELEqD4OpkOR/LlpqRnx1eYh7gcRntz/oL6idQ4ahCri/GMvnnaAb3wPZQSqYz7JIDAl8fBRhsdmIcpjvoLZGenMT31nhgKTO3pD+Ijmfe0DdfgOmVXQdM/gaqBxG6Wv0LS+rSgwKhC0gkizWYveoXD6OxgbVQo5+toFUEsMRuJlwQMCvcjvbSEwxRlGa17aLqQ9FQgacxYl0WqgGVBgzxiUkvbhl49nmuRg+gJkshnv10NenUTsJDJ/VoPfqUe8lIIl4dAt6CFElVN8iWBnF55A3pekiTgOsEKf95zbeDjuxr89HQVubUwC7enb7Lq/ioQkw7okkYEObIk0tpvGUMhU4gTnrrmM465yL5LhPQXuKKhi3fuOaIzKw/P5/41WrdWB9TVbhWMx70kWmNgGBczZxlv9aRU60qOWSJqO9HTV/AHP6P5O7c3YB0UY7AinE73xPlkPSDUjUUyrafW44qblzhsgwdQzWw/jVO4bdKrT4fhApZPj9CQ8rBl7v9mb63Tpo8NKF3cid
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

