apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDIbLbhUL4XvuE6HWGivmMNaY6TDlecPtsFnCeFEPM5MfvndRg2MOvTD/8KfCiLNRf1WvlsSERPMb+RL4Hrp/hopffJM2j4FQ0P7g0w9RhvGt9nV2D/RpRcNmd163t7psfVjbTlEQJL727qsklxJVqa+PFeXlJF0+pt/YRkHoI/T9q0vYNOTEjssRR0wuwyJjP9GuIbhN0DRLhFrLQDVCajm+ssHTXPmddxMue4TSfg/5KmTqNiLVDri3JJ3xX/n9OerLjLhIMCouXrOe7tIT47dhHhuho72UdVO+NjLK2PjMLnX4FfDJq+Yz8WgVFJJAsZeCDne1zUD+k6ITKoHZy/J4HD686K1Dez7T7/ybSQHfm1o5J+TsBafqZAVeA2j5Vh8Wxk+fkIzqAFPB5OSgfebau0Dj+l28vEdRErWo0Q5aWi3vmoRc38PD42mIw20STTwHimcmUB8nUIbNRT7WW0vfCritqN7KoW8woEb6WN9OTLxNk1XNJqoBLyxbaSKNiO2Tv47y7tr53bnVmy2rrbTcvDAhqbQprhEVgp8TcsIaMGf39iKHFoT3i1SiGl8hHCCa4y80GJHlz/E0M5mDundzy/SgFmaA/Bn0D1VD6lHGrgF9p3afqKli2endmn9y8hJE1BC57xtM+bOexRYk6P4rgp3qlqZ1iVc/NBB7aqew7fZ0Q0Zrmyvn+1VVnqur1hrah+WZ2g4hNdRMCozcPau0U1f+Toh/1fpRftGP+1TWr91zgQWhTa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

