apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCG6ZZ4HThNAgjGwHzCj8lmUEsVr2pUDHk+ymI469eBztdX0fxR9qg6zpdKb7alvTjFW2RJMe3Ho8ZWoSwXvsxrm4OooRmHU7/KgIxF2S15LndWw4/f0bGrdhWvSfQQ1SPoN6U4Zxp3IlbS+brrA92P6h975hAoY5zVdVeKDKmzoDf0z/ecBGn++pPoDv5JE98L8x+k7S6WCMURst8SDrU+lZF0sXBbL/nIqrg4FP4oOEIHSXZAoE18RpDkf/iR13RTgWKkxvFwtEMv1exmyliguvMQrAUEJBdf5661cpbjckBbLvM3ny3wIC4LvlTXt7l22iQ5jHA7LkmXKRNOYOai8vgGGyEqIRXayTOsJqsY0l3UdYdRA4YUeqhrGVAJV9DTAsgLr3hYdK7NiE+pQpYBGP7Ue6zZUpnRtUQYxIY7kI9tWA+IWJw8q/76o94dvtyp+Ts6206lmxubEEVT0p+9v7/k3BsI5PAyCYvqU2Mv/PS6BPiX8RGLhL/fJP8LYpM4zIwxyZ6QmxdajhlgEdsR2nWmce+5wVldKVxo6V+GNKtk+DmNGr+iin+qhKiEIdydcyiohXoMdm4UxZj+lPQqe4mfREPSVTemfsYHE/YdxQg8/9X4pbZLcp1Cbhb2ZzAxfb1BMRF7PmJB9xvzsKgd0F3Ao6AG83XuRkda+yTN41k4Kw8zlbbbCwIf1Nc6Ui+k6KNK8R5Aebw0il/zpqPO4S9sHuhhZqSQi3p7zm16JlhqogcIqdT9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

