apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAPoFsdRuYamQBKFbKRLA14aZ8hP6ox6esjhzr7y9zuTBSHdys3nG3XkTSib28rNkhLkLO0Vrk5YrCRNDVHDdYgSdWj650HuoIWimqcoAtlrILX3+ChRNYLy0d8kMO2GOjJoWkT26LFVXWTPJLrNVD94p6RYHdZE3o4PB1bWY5YxP9BbOG45NCvefo/04YNXw3wY44hTb7QtPRsEUfHhNvBdmaegLnmOFiVYeyLeYnLM1O33DkZgj6vowFlHU7PSAq/ZB/UaMJ6PNMW7yblnq0sGLt5pbtsc3gQGcjuWUCH6pstrJ+V7tv9cTqR1/rfnI8I2Rj686My8CMRgUv6LvHbVGTs18N4FU+KKgem8JamBEihhuJPk5Lv6HN0lu4EwM9vcbsYkiKv8hF3U0yCjmAAY+dAY8NwKCzM6m/5T3S2gLi1qvzpRr8CyMfGCcuWL9Gx9wfCi9XRa52W/IJBKXXq8K3Mr7OsHd568qENPLuv4IjNfBJU+VDF7n8tY9jPAQ6vEByeRMAvyiESz/s5mtCOrQkw8fPS0a+VrhZOnc1KBZelBxs7jzu0SZGlAXWGRB1x8zsUL4fvoK36U3TIuGeLrkdoK4AOwkdi2cVbZzmx4fupxhMlQV0TFqOKyVjgaRYsFZ1hXX0vsHFK78j6T3TzBfxJTCWuL9I+yIZpDDbj7KXIVUxpfAvPVKDWmdgtOQ2DOwFBdTBKixBlsTxcLmhKzkGbJaO+O/CqP1ICXGY/k2n60feOEs0n
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

